# Dependabot Configuration
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" 
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/Denver"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    assignees:
      - caleb-wells
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "auto-update"
